name: Deploy Qiniu

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm docs:build

      - name: Publish
        run: pnpm run publish
        env:
          QINIU_ACCESS_KEY: ${{secrets.QINIU_ACCESS_KEY}}
          QINIU_SECRET_KEY: ${{secrets.QINIU_SECRET_KEY}}
          QINIU_BUCKET: ${{secrets.QINIU_BUCKET}}
          QINIU_ZONE: ${{secrets.QINIU_ZONE}}
